name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run linter
        run: flutter analyze --fatal-infos

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /Name-Generator-Extension/
          webRenderer: html
          customArgs: --no-tree-shake-icons